security:

    hide_user_not_found: false

    encoders:
        AppBundle\Entity\User: sha512

    providers:
        db:
            id: app_oauth_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
                        
#        default:
#            anonymous: ~

        secured_area:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login-check
                       
            logout:
                path:   /logout
                target: /login
            
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"

                login_path: /login
                failure_path: /login

                oauth_user_provider:
                    service: app_oauth_user_provider

    access_control:
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }    
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-check, roles: IS_AUTHENTICATED_ANONYMOUSLY }                
        - { path: ^/, roles: ROLE_USER } 
